/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Settings */
    get: operations['get_settings']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/pages/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Page */
    get: operations['get_page']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Projects */
    get: operations['list_projects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/projects/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Project */
    get: operations['get_project']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/people': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List People */
    get: operations['list_people']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/clients': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Clients */
    get: operations['list_clients']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/vacancies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Vacancies */
    get: operations['list_vacancies']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/leads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Lead */
    post: operations['create_lead']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AboutTextDataRead */
    AboutTextDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Body */
      body: string
      media?: components['schemas']['MediaRead'] | null
      /**
       * Layout
       * @enum {string}
       */
      layout: 'text_only' | 'media_left' | 'media_right'
    }
    /** AboutTextSection */
    AboutTextSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'about_text'
      data: components['schemas']['AboutTextDataRead']
    }
    /** CapabilitiesDataRead */
    CapabilitiesDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro?: string | null
      /**
       * Items
       * @default []
       */
      items: components['schemas']['IconItemRead'][]
      /**
       * Columns
       * @enum {integer}
       */
      columns: 2 | 3 | 4
    }
    /** CapabilitiesSection */
    CapabilitiesSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'capabilities'
      data: components['schemas']['CapabilitiesDataRead']
    }
    /** ClientRead */
    ClientRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      logo: components['schemas']['MediaRead'] | null
      /** Industry */
      industry: string
      /** Industry Label */
      industry_label: string
      /** Description */
      description: string
      testimonial: components['schemas']['TestimonialRead'] | null
      /** Website Url */
      website_url: string | null
    }
    /** ClientsGridDataRead */
    ClientsGridDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Show Industry Filter */
      show_industry_filter: boolean
      /**
       * Clients
       * @default []
       */
      clients: components['schemas']['ClientRead'][]
    }
    /** ClientsGridSection */
    ClientsGridSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'clients_grid'
      data: components['schemas']['ClientsGridDataRead']
    }
    /** ClientsMarqueeDataRead */
    ClientsMarqueeDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Clients
       * @default []
       */
      clients: components['schemas']['ClientRead'][]
    }
    /** ClientsMarqueeSection */
    ClientsMarqueeSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'clients_marquee'
      data: components['schemas']['ClientsMarqueeDataRead']
    }
    /** ContactFormDataRead */
    ContactFormDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Text */
      text?: string | null
      /** Lead Types */
      lead_types: components['schemas']['LeadType'][]
      default_type: components['schemas']['LeadType']
      /** Consent Text */
      consent_text: string
      /** Success Text */
      success_text: string
    }
    /** ContactFormSection */
    ContactFormSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'contact_form'
      data: components['schemas']['ContactFormDataRead']
    }
    /** ContactsRead */
    ContactsRead: {
      /** Address */
      address: string
      /** Phones */
      phones: string[]
      /** Email */
      email: string | null
      /** Whatsapp */
      whatsapp: string | null
      /** Hours */
      hours: string | null
      coordinates: components['schemas']['Coordinates'] | null
    }
    /** Coordinates */
    Coordinates: {
      /** Lat */
      lat: number
      /** Lng */
      lng: number
    }
    /** CountryRead */
    CountryRead: {
      /** Code */
      code: string
      /** Name */
      name: string
      /** Note */
      note: string | null
    }
    /** CtaDataRead */
    CtaDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Text */
      text?: string | null
      /**
       * Ctas
       * @default []
       */
      ctas: components['schemas']['CtaRead'][]
      media?: components['schemas']['MediaRead'] | null
    }
    /** CtaRead */
    CtaRead: {
      /** Label */
      label: string
      /** Href */
      href: string
      /**
       * Variant
       * @enum {string}
       */
      variant: 'primary' | 'secondary'
    }
    /** CtaSection */
    CtaSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'cta'
      data: components['schemas']['CtaDataRead']
    }
    /** DivisionRead */
    DivisionRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Slug */
      slug: string
      /** Name */
      name: string
      /** Tagline */
      tagline: string
      /** Description */
      description: string
      logo: components['schemas']['MediaRead'] | null
      cover: components['schemas']['MediaRead'] | null
      /** Stats */
      stats: components['schemas']['DivisionStat'][]
      /** Website Url */
      website_url: string | null
      /** Page Slug */
      page_slug: string | null
    }
    /** DivisionRef */
    DivisionRef: {
      /** Slug */
      slug: string
      /** Name */
      name: string
    }
    /** DivisionStat */
    DivisionStat: {
      /** Value */
      value: number
      /** Suffix */
      suffix: string
      /** Label */
      label: string
    }
    /** DivisionsGridDataRead */
    DivisionsGridDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Divisions
       * @default []
       */
      divisions: components['schemas']['DivisionRead'][]
    }
    /** DivisionsGridSection */
    DivisionsGridSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'divisions_grid'
      data: components['schemas']['DivisionsGridDataRead']
    }
    /**
     * EmploymentType
     * @enum {string}
     */
    EmploymentType: 'full_time' | 'part_time' | 'contract' | 'internship'
    /** FactRead */
    FactRead: {
      /** Value */
      value: string
      /** Label */
      label: string
    }
    /** FooterRead */
    FooterRead: {
      /** Text */
      text: string
      /** Legal */
      legal: string
    }
    /** GeographyDataRead */
    GeographyDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro?: string | null
      /**
       * Countries
       * @default []
       */
      countries: components['schemas']['CountryRead'][]
    }
    /** GeographySection */
    GeographySection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'geography'
      data: components['schemas']['GeographyDataRead']
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Health */
    Health: {
      /** Status */
      status: string
      /** Database */
      database: boolean
      /** Storage */
      storage: boolean
    }
    /** HeroDataRead */
    HeroDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Subtitle */
      subtitle?: string | null
      background?: components['schemas']['MediaRead'] | null
      video?: components['schemas']['MediaRead'] | null
      /**
       * Ctas
       * @default []
       */
      ctas: components['schemas']['CtaRead'][]
      /**
       * Swatches
       * @default []
       */
      swatches: components['schemas']['SwatchRead'][]
    }
    /** HeroSection */
    HeroSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'hero'
      data: components['schemas']['HeroDataRead']
    }
    /** IconItemRead */
    IconItemRead: {
      /** Icon */
      icon: string
      /** Title */
      title: string
      /** Text */
      text: string
      media: components['schemas']['MediaRead'] | null
    }
    /** LeadCreate */
    LeadCreate: {
      /** Name */
      name: string
      /** Phone */
      phone?: string | null
      /** Email */
      email?: string | null
      /** Message */
      message?: string | null
      type: components['schemas']['LeadType']
      /** Source Page */
      source_page?: string | null
      /** @default ru */
      locale: components['schemas']['Locale']
      /** Website */
      website?: string | null
    }
    /** LeadCreated */
    LeadCreated: {
      /** Id */
      id: string | null
      /**
       * Ok
       * @default true
       */
      ok: boolean
    }
    /**
     * LeadType
     * @enum {string}
     */
    LeadType: 'investor' | 'partner' | 'candidate' | 'client'
    /**
     * Locale
     * @enum {string}
     */
    Locale: 'ru' | 'kk' | 'en'
    /** MediaGalleryDataRead */
    MediaGalleryDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Items
       * @default []
       */
      items: components['schemas']['MediaRead'][]
      /**
       * Layout
       * @enum {string}
       */
      layout: 'grid' | 'strip'
    }
    /** MediaGallerySection */
    MediaGallerySection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'media_gallery'
      data: components['schemas']['MediaGalleryDataRead']
    }
    /** MediaPlaceholder */
    MediaPlaceholder: {
      /** Dominant Color */
      dominant_color?: string | null
      /** Blurhash */
      blurhash?: string | null
    }
    /** MediaRead */
    MediaRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Url */
      url: string
      /** Width */
      width: number
      /** Height */
      height: number
      /** Alt */
      alt: string
      /** Mime Type */
      mime_type: string
      placeholder: components['schemas']['MediaPlaceholder']
    }
    /** NavItemRead */
    NavItemRead: {
      /** Label */
      label: string
      /** Page Slug */
      page_slug: string | null
      /** Anchor */
      anchor: string | null
      /** Url */
      url: string | null
    }
    /** PageRead */
    PageRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Slug */
      slug: string
      /** Title */
      title: string
      seo: components['schemas']['PageSeo']
      /** Sections */
      sections: (
        | components['schemas']['HeroSection']
        | components['schemas']['StatsSection']
        | components['schemas']['AboutTextSection']
        | components['schemas']['TimelineSection']
        | components['schemas']['DivisionsGridSection']
        | components['schemas']['ProjectsShowcaseSection']
        | components['schemas']['ProjectListSection']
        | components['schemas']['CapabilitiesSection']
        | components['schemas']['ProcessStepsSection']
        | components['schemas']['ProductionSection']
        | components['schemas']['TokenizationSection']
        | components['schemas']['TeamGridSection']
        | components['schemas']['ClientsMarqueeSection']
        | components['schemas']['ClientsGridSection']
        | components['schemas']['TestimonialsSection']
        | components['schemas']['QuoteSection']
        | components['schemas']['CtaSection']
        | components['schemas']['ContactFormSection']
        | components['schemas']['MediaGallerySection']
        | components['schemas']['VideoSection']
        | components['schemas']['VacanciesSection']
        | components['schemas']['GeographySection']
      )[]
    }
    /** PageSeo */
    PageSeo: {
      /** Title */
      title: string
      /** Description */
      description: string
      og_image: components['schemas']['MediaRead'] | null
    }
    /** PersonRead */
    PersonRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Full Name */
      full_name: string
      /** Position */
      position: string
      /** Bio */
      bio: string
      photo: components['schemas']['MediaRead'] | null
      /** Linkedin Url */
      linkedin_url: string | null
      /** Is Key */
      is_key: boolean
      /** Is Founder */
      is_founder: boolean
      division: components['schemas']['DivisionRef'] | null
    }
    /** ProcessStepRead */
    ProcessStepRead: {
      /** Title */
      title: string
      /** Text */
      text: string
      media: components['schemas']['MediaRead'] | null
      division: components['schemas']['DivisionRead'] | null
    }
    /** ProcessStepsDataRead */
    ProcessStepsDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro?: string | null
      /**
       * Steps
       * @default []
       */
      steps: components['schemas']['ProcessStepRead'][]
    }
    /** ProcessStepsSection */
    ProcessStepsSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'process_steps'
      data: components['schemas']['ProcessStepsDataRead']
    }
    /** ProductionDataRead */
    ProductionDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Body */
      body: string
      /**
       * Facts
       * @default []
       */
      facts: components['schemas']['FactRead'][]
      /**
       * Gallery
       * @default []
       */
      gallery: components['schemas']['MediaRead'][]
    }
    /** ProductionSection */
    ProductionSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'production'
      data: components['schemas']['ProductionDataRead']
    }
    /** ProjectCard */
    ProjectCard: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Slug */
      slug: string
      /** Title */
      title: string
      status: components['schemas']['ProjectStatus']
      /** Location */
      location: string
      /** Year */
      year: number | null
      /** Area M2 */
      area_m2: number | null
      /** Short Description */
      short_description: string
      cover: components['schemas']['MediaRead'] | null
      /** Tags */
      tags: string[]
      /** Is Featured */
      is_featured: boolean
      /** Is Tokenized */
      is_tokenized: boolean
      division: components['schemas']['DivisionRef'] | null
    }
    /** ProjectListDataRead */
    ProjectListDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Show Filter */
      show_filter: boolean
      /**
       * Projects
       * @default []
       */
      projects: components['schemas']['ProjectCard'][]
    }
    /** ProjectListSection */
    ProjectListSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'project_list'
      data: components['schemas']['ProjectListDataRead']
    }
    /** ProjectRead */
    ProjectRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Slug */
      slug: string
      /** Title */
      title: string
      status: components['schemas']['ProjectStatus']
      /** Location */
      location: string
      /** Year */
      year: number | null
      /** Area M2 */
      area_m2: number | null
      /** Short Description */
      short_description: string
      cover: components['schemas']['MediaRead'] | null
      /** Tags */
      tags: string[]
      /** Is Featured */
      is_featured: boolean
      /** Is Tokenized */
      is_tokenized: boolean
      division: components['schemas']['DivisionRef'] | null
      /** Body */
      body: string
      /** Gallery */
      gallery: components['schemas']['MediaRead'][]
    }
    /**
     * ProjectStatus
     * @enum {string}
     */
    ProjectStatus: 'completed' | 'in_progress' | 'planned'
    /** ProjectsShowcaseDataRead */
    ProjectsShowcaseDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Projects
       * @default []
       */
      projects: components['schemas']['ProjectCard'][]
      link?: components['schemas']['CtaRead'] | null
    }
    /** ProjectsShowcaseSection */
    ProjectsShowcaseSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'projects_showcase'
      data: components['schemas']['ProjectsShowcaseDataRead']
    }
    /** QuoteDataRead */
    QuoteDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Text */
      text: string
      person?: components['schemas']['PersonRead'] | null
      media?: components['schemas']['MediaRead'] | null
    }
    /** QuoteSection */
    QuoteSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'quote'
      data: components['schemas']['QuoteDataRead']
    }
    /** SeoRead */
    SeoRead: {
      /** Title */
      title: string
      /** Description */
      description: string
      og_image: components['schemas']['MediaRead'] | null
    }
    /** SiteSettingsRead */
    SiteSettingsRead: {
      /** Site Name */
      site_name: string
      logo: components['schemas']['MediaRead'] | null
      /** Navigation */
      navigation: components['schemas']['NavItemRead'][]
      contacts: components['schemas']['ContactsRead']
      /** Socials */
      socials: components['schemas']['Social'][]
      footer: components['schemas']['FooterRead']
      default_seo: components['schemas']['SeoRead']
    }
    /** Social */
    Social: {
      /** Type */
      type: string
      /** Url */
      url: string
    }
    /** StatRead */
    StatRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Value */
      value: number
      /** Prefix */
      prefix: string | null
      /** Suffix */
      suffix: string
      /** Label */
      label: string
    }
    /** StatsDataRead */
    StatsDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Stats
       * @default []
       */
      stats: components['schemas']['StatRead'][]
    }
    /** StatsSection */
    StatsSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'stats'
      data: components['schemas']['StatsDataRead']
    }
    /** SwatchRead */
    SwatchRead: {
      /** Code */
      code: string
      /** Label */
      label: string
      /** Color */
      color: string
      /**
       * Finish
       * @enum {string}
       */
      finish: 'matte' | 'gloss' | 'texture'
    }
    /** TeamGridDataRead */
    TeamGridDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro?: string | null
      /**
       * Mode
       * @enum {string}
       */
      mode: 'founder' | 'key' | 'rest' | 'all'
      /** Show Division Filter */
      show_division_filter: boolean
      /**
       * People
       * @default []
       */
      people: components['schemas']['PersonRead'][]
    }
    /** TeamGridSection */
    TeamGridSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'team_grid'
      data: components['schemas']['TeamGridDataRead']
    }
    /** TestimonialRead */
    TestimonialRead: {
      /** Quote */
      quote: string
      /** Author */
      author: string
      /** Position */
      position: string
    }
    /** TestimonialsDataRead */
    TestimonialsDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Clients
       * @default []
       */
      clients: components['schemas']['ClientRead'][]
    }
    /** TestimonialsSection */
    TestimonialsSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'testimonials'
      data: components['schemas']['TestimonialsDataRead']
    }
    /** TimelineDataRead */
    TimelineDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /**
       * Events
       * @default []
       */
      events: components['schemas']['TimelineEventRead'][]
    }
    /** TimelineEventRead */
    TimelineEventRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Year */
      year: number
      /** Title */
      title: string
      /** Description */
      description: string
      image: components['schemas']['MediaRead'] | null
    }
    /** TimelineSection */
    TimelineSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'timeline'
      data: components['schemas']['TimelineDataRead']
    }
    /** TokenizationDataRead */
    TokenizationDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro: string
      /**
       * Steps
       * @default []
       */
      steps: components['schemas']['IconItemRead'][]
      /**
       * Benefits
       * @default []
       */
      benefits: string[]
      /** Disclaimer */
      disclaimer: string
      /**
       * Projects
       * @default []
       */
      projects: components['schemas']['ProjectCard'][]
    }
    /** TokenizationSection */
    TokenizationSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'tokenization_explainer'
      data: components['schemas']['TokenizationDataRead']
    }
    /**
     * Tone
     * @enum {string}
     */
    Tone: 'dark' | 'light' | 'accent'
    /** VacanciesDataRead */
    VacanciesDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Intro */
      intro?: string | null
      /**
       * Vacancies
       * @default []
       */
      vacancies: components['schemas']['VacancyRead'][]
      /** Empty Text */
      empty_text?: string | null
    }
    /** VacanciesSection */
    VacanciesSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'vacancies'
      data: components['schemas']['VacanciesDataRead']
    }
    /** VacancyRead */
    VacancyRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Title */
      title: string
      /** Location */
      location: string
      employment_type: components['schemas']['EmploymentType']
      /** Description */
      description: string
      division: components['schemas']['DivisionRef'] | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VideoDataRead */
    VideoDataRead: {
      /** Eyebrow */
      eyebrow?: string | null
      /** Title */
      title?: string | null
      /** Embed Url */
      embed_url?: string | null
      video?: components['schemas']['MediaRead'] | null
      poster?: components['schemas']['MediaRead'] | null
    }
    /** VideoSection */
    VideoSection: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Anchor */
      anchor: string | null
      tone: components['schemas']['Tone']
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'video'
      data: components['schemas']['VideoDataRead']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  get_settings: {
    parameters: {
      query?: {
        locale?: components['schemas']['Locale']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SiteSettingsRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_page: {
    parameters: {
      query?: {
        locale?: components['schemas']['Locale']
      }
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PageRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_projects: {
    parameters: {
      query?: {
        division?: string | null
        status?: components['schemas']['ProjectStatus'] | null
        featured?: boolean | null
        locale?: components['schemas']['Locale']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectCard'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_project: {
    parameters: {
      query?: {
        locale?: components['schemas']['Locale']
      }
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_people: {
    parameters: {
      query?: {
        division?: string | null
        key?: boolean | null
        locale?: components['schemas']['Locale']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PersonRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_clients: {
    parameters: {
      query?: {
        locale?: components['schemas']['Locale']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ClientRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_vacancies: {
    parameters: {
      query?: {
        locale?: components['schemas']['Locale']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VacancyRead'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_lead: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LeadCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeadCreated']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
