"""collection versions

Revision ID: 8fd9dba8e086
Revises: ea65b599be4e
Create Date: 2026-10-07 14:58:58.719645
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8fd9dba8e086"
down_revision: str | None = "ea65b599be4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "division", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("person", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("project", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("stat", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "timeline_event", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("vacancy", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "version")
    op.drop_column("timeline_event", "version")
    op.drop_column("stat", "version")
    op.drop_column("project", "version")
    op.drop_column("person", "version")
    op.drop_column("division", "version")
    op.drop_column("client", "version")
    # ### end Alembic commands ###
