"""page and section version

Revision ID: ea65b599be4e
Revises: ff499fb67ef7
Create Date: 2026-10-07 14:42:49.763980
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ea65b599be4e"
down_revision: str | None = "ff499fb67ef7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("section", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("section", "version")
    op.drop_column("page", "version")
    # ### end Alembic commands ###
