"""media library columns

Revision ID: ff499fb67ef7
Revises: 06b6392ee7ae
Create Date: 2026-10-07 14:20:17.878090
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ff499fb67ef7"
down_revision: str | None = "06b6392ee7ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("original_filename", sa.String(length=255), nullable=True))
    op.add_column("media", sa.Column("folder", sa.String(length=128), nullable=True))
    op.add_column(
        "media",
        sa.Column("tags", sa.ARRAY(sa.String(length=64)), server_default="{}", nullable=False),
    )
    op.add_column(
        "media", sa.Column("status", sa.String(length=16), server_default="ready", nullable=False)
    )
    op.add_column("media", sa.Column("uploaded_by", sa.UUID(), nullable=True))
    op.add_column(
        "media",
        sa.Column(
            "variants", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("media", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.create_index(op.f("ix_media_folder"), "media", ["folder"], unique=False)
    op.create_index(op.f("ix_media_status"), "media", ["status"], unique=False)
    op.create_foreign_key(
        op.f("fk_media_uploaded_by_admin_user"),
        "media",
        "admin_user",
        ["uploaded_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_media_uploaded_by_admin_user"), "media", type_="foreignkey")
    op.drop_index(op.f("ix_media_status"), table_name="media")
    op.drop_index(op.f("ix_media_folder"), table_name="media")
    op.drop_column("media", "version")
    op.drop_column("media", "variants")
    op.drop_column("media", "uploaded_by")
    op.drop_column("media", "status")
    op.drop_column("media", "tags")
    op.drop_column("media", "folder")
    op.drop_column("media", "original_filename")
    # ### end Alembic commands ###
