"""lead status, manager note and version; site settings version

Revision ID: 97d1653f9678
Revises: 8fd9dba8e086
Create Date: 2026-10-08 10:09:59.253732
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "97d1653f9678"
down_revision: str | None = "8fd9dba8e086"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lead", sa.Column("status", sa.String(length=16), server_default="new", nullable=False)
    )
    op.add_column("lead", sa.Column("manager_note", sa.Text(), nullable=True))
    op.add_column("lead", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.create_index(op.f("ix_lead_status"), "lead", ["status"], unique=False)
    op.add_column(
        "site_settings", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_settings", "version")
    op.drop_index(op.f("ix_lead_status"), table_name="lead")
    op.drop_column("lead", "version")
    op.drop_column("lead", "manager_note")
    op.drop_column("lead", "status")
    # ### end Alembic commands ###
