"""initial schema

Revision ID: 83546b7f721d
Revises:
Create Date: 2026-10-03 10:35:19.566946
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "83546b7f721d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("source_page", sa.String(length=256), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead")),
    )
    op.create_index(op.f("ix_lead_type"), "lead", ["type"], unique=False)
    op.create_table(
        "media",
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("alt", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blurhash", sa.String(length=64), nullable=True),
        sa.Column("dominant_color", sa.String(length=7), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("bucket", "s3_key", name="bucket_key"),
    )
    op.create_table(
        "stat",
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=True),
        sa.Column("suffix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stat")),
    )
    op.create_index(op.f("ix_stat_context"), "stat", ["context"], unique=False)
    op.create_index(op.f("ix_stat_is_published"), "stat", ["is_published"], unique=False)
    op.create_table(
        "client",
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo_id", sa.UUID(), nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=False),
        sa.Column("industry_label", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("testimonial", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("website_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["logo_id"], ["media.id"], name=op.f("fk_client_logo_id_media"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
    )
    op.create_index(op.f("ix_client_industry"), "client", ["industry"], unique=False)
    op.create_index(op.f("ix_client_is_published"), "client", ["is_published"], unique=False)
    op.create_table(
        "division",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tagline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo_id", sa.UUID(), nullable=True),
        sa.Column("cover_id", sa.UUID(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("website_url", sa.String(length=512), nullable=True),
        sa.Column("page_slug", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cover_id"], ["media.id"], name=op.f("fk_division_cover_id_media"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["logo_id"], ["media.id"], name=op.f("fk_division_logo_id_media"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_division")),
        sa.UniqueConstraint("slug", name=op.f("uq_division_slug")),
    )
    op.create_index(op.f("ix_division_is_published"), "division", ["is_published"], unique=False)
    op.create_table(
        "page",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo_title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo_description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("og_image_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["og_image_id"],
            ["media.id"],
            name=op.f("fk_page_og_image_id_media"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page")),
        sa.UniqueConstraint("slug", name=op.f("uq_page_slug")),
    )
    op.create_index(op.f("ix_page_is_published"), "page", ["is_published"], unique=False)
    op.create_table(
        "site_settings",
        sa.Column("site_name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo_id", sa.UUID(), nullable=True),
        sa.Column("navigation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("socials", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("footer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("default_seo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["logo_id"],
            ["media.id"],
            name=op.f("fk_site_settings_logo_id_media"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_settings")),
    )
    op.create_table(
        "timeline_event",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["media.id"],
            name=op.f("fk_timeline_event_image_id_media"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_event")),
    )
    op.create_index(
        op.f("ix_timeline_event_is_published"), "timeline_event", ["is_published"], unique=False
    )
    op.create_table(
        "person",
        sa.Column("full_name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=True),
        sa.Column("bio", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("photo_id", sa.UUID(), nullable=True),
        sa.Column("linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("is_key", sa.Boolean(), nullable=False),
        sa.Column("is_founder", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
            name=op.f("fk_person_division_id_division"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"], ["media.id"], name=op.f("fk_person_photo_id_media"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
    )
    op.create_index(op.f("ix_person_division_id"), "person", ["division_id"], unique=False)
    op.create_index(op.f("ix_person_is_published"), "person", ["is_published"], unique=False)
    op.create_table(
        "project",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("short_description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cover_id", sa.UUID(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_tokenized", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cover_id"], ["media.id"], name=op.f("fk_project_cover_id_media"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
            name=op.f("fk_project_division_id_division"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("slug", name=op.f("uq_project_slug")),
    )
    op.create_index(op.f("ix_project_division_id"), "project", ["division_id"], unique=False)
    op.create_index(op.f("ix_project_is_featured"), "project", ["is_featured"], unique=False)
    op.create_index(op.f("ix_project_is_published"), "project", ["is_published"], unique=False)
    op.create_index(op.f("ix_project_status"), "project", ["status"], unique=False)
    op.create_table(
        "section",
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("anchor", sa.String(length=64), nullable=True),
        sa.Column("tone", sa.String(length=16), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["page.id"], name=op.f("fk_section_page_id_page"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section")),
    )
    op.create_index(op.f("ix_section_page_id"), "section", ["page_id"], unique=False)
    op.create_table(
        "vacancy",
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=True),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("employment_type", sa.String(length=16), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
            name=op.f("fk_vacancy_division_id_division"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy")),
    )
    op.create_index(op.f("ix_vacancy_is_published"), "vacancy", ["is_published"], unique=False)
    op.create_table(
        "project_media",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_project_media_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_media_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "media_id", name=op.f("pk_project_media")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_media")
    op.drop_index(op.f("ix_vacancy_is_published"), table_name="vacancy")
    op.drop_table("vacancy")
    op.drop_index(op.f("ix_section_page_id"), table_name="section")
    op.drop_table("section")
    op.drop_index(op.f("ix_project_status"), table_name="project")
    op.drop_index(op.f("ix_project_is_published"), table_name="project")
    op.drop_index(op.f("ix_project_is_featured"), table_name="project")
    op.drop_index(op.f("ix_project_division_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_person_is_published"), table_name="person")
    op.drop_index(op.f("ix_person_division_id"), table_name="person")
    op.drop_table("person")
    op.drop_index(op.f("ix_timeline_event_is_published"), table_name="timeline_event")
    op.drop_table("timeline_event")
    op.drop_table("site_settings")
    op.drop_index(op.f("ix_page_is_published"), table_name="page")
    op.drop_table("page")
    op.drop_index(op.f("ix_division_is_published"), table_name="division")
    op.drop_table("division")
    op.drop_index(op.f("ix_client_is_published"), table_name="client")
    op.drop_index(op.f("ix_client_industry"), table_name="client")
    op.drop_table("client")
    op.drop_index(op.f("ix_stat_is_published"), table_name="stat")
    op.drop_index(op.f("ix_stat_context"), table_name="stat")
    op.drop_table("stat")
    op.drop_table("media")
    op.drop_index(op.f("ix_lead_type"), table_name="lead")
    op.drop_table("lead")
    # ### end Alembic commands ###
