import { useState } from 'react'
import type { Media } from '@/api/types'
import { cn } from '@/lib/cn'
import { buildImageUrl } from '@/lib/image'

type Props = {
  media: Media | null | undefined
  /** `sizes` attribute, needed once srcset is generated by the image proxy. */
  sizes?: string
  className?: string
  imgClassName?: string
  /** Above-the-fold images load eagerly with high priority. */
  priority?: boolean
  /** Fill the parent box; the parent sets both width and height. */
  fill?: boolean
  /** Crop to the aspect ratio set by an `aspect-*` class in className instead of the media's own. */
  crop?: boolean
  fit?: 'cover' | 'contain'
}

/** The only way to render a CMS image: reserved space, placeholder color, lazy loading. */
export function SmartImage({
  media,
  sizes,
  className,
  imgClassName,
  priority,
  fill,
  crop,
  fit = 'cover',
}: Props) {
  const [loaded, setLoaded] = useState(false)
  if (!media) return <div className={cn('bg-tile', className)} aria-hidden="true" />
  // Logos and other transparent images must not sit on a solid placeholder of their own color.
  const opaque = fit === 'cover' && media.mime_type !== 'image/svg+xml'

  return (
    <div
      className={cn('relative overflow-hidden', fill && 'h-full w-full', crop && 'w-full', className)}
      style={{
        backgroundColor: opaque ? (media.placeholder.dominant_color ?? undefined) : undefined,
        aspectRatio: fill || crop ? undefined : `${media.width} / ${media.height}`,
      }}
    >
      <img
        src={buildImageUrl(media)}
        alt={media.alt}
        width={media.width}
        height={media.height}
        sizes={sizes}
        loading={priority ? 'eager' : 'lazy'}
        // React 18 does not know `fetchPriority`; the lowercase attribute passes through as is.
        {...{ fetchpriority: priority ? 'high' : 'auto' }}
        decoding="async"
        onLoad={() => setLoaded(true)}
        className={cn(
          'absolute inset-0 h-full w-full transition-opacity duration-500',
          fit === 'cover' ? 'object-cover' : 'object-contain',
          loaded ? 'opacity-100' : 'opacity-0',
          imgClassName,
        )}
      />
    </div>
  )
}
